master: test

diff --git a/bin/detect b/bin/detect
--- a/bin/detect
+++ b/bin/detect
@@ -1,10 +1,10 @@
 #!/usr/bin/env bash
 # bin/detect <build-dir>
 
-if [ -f $1/Shellfile ]; then
-  echo "Shell"
+if [ -f $1/shell_build.sh ]; then
+  echo "shell_build"
   exit 0
 else
-  echo "Could not find an 'Shellfile'! Please ensure it exists and is checked into Git." >&2
+  echo "Could not find an 'shell_build'! Please ensure it exists and is checked into Git." >&2
   exit 1
 fi
